name: Build Extension with PNPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create firefox build
        env:
          TARGET_BROWSER: firefox
        run: pnpm build

      - name: Upload firefox build output
        uses: actions/upload-artifact@v4
        with:
          name: firefox-${{ github.sha }}
          path: dist/*

      - name: Create chrome build
        env:
          TARGET_BROWSER: chrome
        run: pnpm build

      - name: Upload chrome build output
        uses: actions/upload-artifact@v4
        with:
          name: chrome-${{ github.sha }}
          path: dist/*
